apiVersion: apps/v1
kind: Deployment
namespace: roboshop
metadata:
  name: catalogue
  labels:
    project: roboshop
    tier: backend
    component: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: backend
      component: catalogue
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: catalogue
    spec:
      containers:
      - name: catalogue
        image: shajuawsdevops/roboshop-docker:catalogue-v1