apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: mysql-headless
  labels:
    app: mysql
    project: roboshop
    tier: db
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3396
    name: mysql
  clusterIP: None
  selector:
    app: mysql
    project: roboshop
    tier: db
---
apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: mysql
  labels:
    app: mysql
    project: roboshop
    tier: db
spec:
  ports:
  - protocol: TCP
    port: 3396
    targetPort: 3396
    name: mysql
  selector:
    app: mysql
    project: roboshop
    tier: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: roboshop
  name: mysql
  labels:
    app: mysql
    project: roboshop
    tier: db
spec:
  selector:
    matchLabels:
      app: mysql
      project: roboshop
      tier: db # has to match .spec.template.metadata.labels
  serviceName: "mysql-headless"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: mysql
        project: roboshop
        tier: db # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mysql
        image: shajuawsdevops/roboshop-docker:mysql-v1
        volumeMounts:
        - name: mysql
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs-sc"
      resources:
        requests:
          storage: 1Gi