apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: roboshop
  labels:
    environment: dev
    project: roboshop
spec:
  containers:
  - name: debug-container
    image: shajuawsdevops/roboshop-docker:debug-v1