name: roboshop
services:
  mongodb:
    build: ./MongoDB
    image: shajuawsdocker/mongodb:v1
    container_name: mongodb
  catalogue:
    build: ./Catalogue
    image: shajuawsdocker/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  Frontend:
    build: ./Frontend
    image: shajuawsdocker/frontend:v1
    container_name: frontend
    ports:
      - 80:80
    depends_on:
      - catalogue
      - user

  redis:
    build: ./redis
    image: shajuawsdocker/redis:v1
    container_name: redis
  user:
    build: ./user
    image: shajuawsdocker/user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis
  cart:
    build: ./cart
    image: shajuawsdocker/cart:v1
    container_name: cart
    environment:
      - REDIS_HOST=redis
      - CATALOGUE_HOST=catalogue
      - CATALOGUE_PORT=8080
    depends_on:
      - redis
      - catalogue
  mysql:
    build: ./mysql
    image: shajuawsdocker/mysql:v1
    container_name: mysql
    command: --mysql-native-password=ON --innodb-lock_wait_timeout=120
    environment:
      MYSQL_ROOT_PASSWORD: RoboShop@1
  shipping:
    build: ./shipping
    image: shajuawsdocker/shipping:v1
    container_name: shipping
    environment:
      - CART_ENDPOINT=cart:8080
      - DB_HOST=mysql
  payment:
    build: ./payment
    image: shajuawsdocker/payment:v1
    container_name: payment
    environment:
      - CART_HOST=cart
      - CART_PORT=8080
      - USER_HOST=user
      - USER_PORT=8080
      - AMQP_HOST=rabbitmq
      - AMQP_USER=roboshop
      - AMQP_PASS=roboshop123
    depends_on:
      - cart
      - user
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123