apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: mongodb-headless
  labels:
    app: mongodb
    project: roboshop
    tier: db
spec:
  ports:
  - protocol: TCP
    port: 27017
    targetport: 27017
    name: mongodb
  clusterIP: None
  selector:
    app: mongodb
    project: roboshop
    tier: db
---
apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: mongodb
  labels:
    app: mongodb
    project: roboshop
    tier: db
spec:
  ports:
  - protocol: TCP
    port: 27017
    targetport: 27017
    name: mongodb
  selector:
    app: mongodb
    project: roboshop
    tier: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: roboshop
  name: mongodb
  labels:
    app: mongodb
    project: roboshop
    tier: db
spec:
  selector:
    matchLabels:
      app: mongodb
      project: roboshop
      tier: db # has to match .spec.template.metadata.labels
  serviceName: "mongodb-headless"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: mongodb
        project: roboshop
        tier: db # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mongodb
        image: shajuawsdevops/roboshop-docker:mongodb-v1
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs-sc"
      resources:
        requests:
          storage: 1Gi