apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: redis-headless
  labels:
    app: redis
    project: roboshop
    tier: db
spec:
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    name: redis
  clusterIP: None
  selector:
    app: redis
    project: roboshop
    tier: db
---
apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: redis
  labels:
    app: redis
    project: roboshop
    tier: db
spec:
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: redis
    project: roboshop
    tier: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: roboshop
  name: redis
  labels:
    app: redis
    project: roboshop
    tier: db
spec:
  selector:
    matchLabels:
      app: redis
      project: roboshop
      tier: db # has to match .spec.template.metadata.labels
  serviceName: "redis-headless"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: redis
        project: roboshop
        tier: db # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: redis
        image: redis:7
        volumeMounts:
        - name: redis
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs-sc"
      resources:
        requests:
          storage: 1Gi